cmd/resource-topology-exporter/main.go, go.mod, go.sum, pkg/resourcemonitor/noderesourcesaggregator.go, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/alias.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/context/context.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/option/option.go, vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go, vendor/modules.txt
allow to use `/host-sys` and not force `/host/sys` (we can still do the latter).
Import ghw package which allows so.
=> cmd: allow to override sysfs mount point

.github/workflows/e2e.yml, cmd/resource-topology-exporter/main.go, go.mod, hack/get-manifest-ds.sh, manifests/resource-topology-exporter-ds.yaml, pkg/nrtupdater/nrtupdater.go, pkg/resourcemonitor/types.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/modules.txt
The "smart polling" idea is all about have more polling triggers than just timer.
We know -and we can pretty much depend on- that kubelet rewrites it checkpoints for resource manager each time a resource
allocation is performed. When this happens, something changed and we can poll again the podresources API to learn what.
This allows much faster response time without the need of having a very frequent poll interval, which is too taxing on steady state.
To quickly learn about the checkpoint changes, we use the standard `fsnotify` linux API using the go package.
The only drawback of this (optional) approach is that RTE now requires RO access to the while kubelet state directory(ies).
=> Add smart polling for RTE

cmd/resource-topology-exporter/main.go, manifests/resource-topology-exporter-ds.yaml, pkg/podrescli/client.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
Until the kubernetes issue https://github.com/kubernetes/kubernetes/issues/102190
is fixed, we can't learn easily from the podresources API which
cpus belong to the shared pool and which cpus are assigned to exclusive
pools. This makes the resource reporting inconsistent.
A possible workaround is to explicitely design a container whose
cpu resources belong to the shared pool. Knowing that, RTE can safely
compute which cpus pertain to which pool when scanning the resources
allocated to each container.
So, we add a minion pause container, which we know for sure
1. it always runs
2. where it runs (namespace, pod name, container name)
3. gets cpus from the shared pool
Then, we point the RTE to it, so it is enabled to fix the cpu reporting.
=> Add and use a minion container to learn about the shared cpu pool

.github/workflows/e2e.yml, Makefile, cmd/resource-topology-exporter/main.go, manifests/resource-topology-exporter-ds.yaml, pkg/podrescli/client.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, test/e2e/e2e_test.go, test/e2e/rte.go, test/e2e/topology_updater.go, test/e2e/utils/nodes.go, test/e2e/utils/pod.go
In this series, we first split the e2e tests in rte and non-rte specific, in order to make as easy as possible to move tests from/to NFD, for the mutual benefict of both projects.
Then, we add some rte-specific e2e tests, focusing on rte-specific features like the minion-container feature or (in the future) the smart polling.
Along the way, we add minor fixes and improvements pulled by the e2e tests and the related development.
=> Add more e2e tests

cmd/resource-topology-exporter/main.go, manifests/resource-topology-exporter-config.yaml, manifests/resource-topology-exporter-ds.yaml, pkg/resourcemonitor/excludelist.go, pkg/resourcemonitor/noderesourcesaggregator.go, pkg/resourcemonitor/noderesourcesaggregator_test.go, pkg/resourcemonitor/types.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
Backport the exclude-list feature from NFD.
The original PR for NFD: kubernetes-sigs/node-feature-discovery#545
For the E2E there is some problem with creating the ConfigMap during the e2e test.
The ConfigMap should be created on the cluster before the RTE container is running (the RTE container consumes the ConfigMap). this is not the case because the RTE container is up and running before the test even starts (it was created by ```kubectl create -f``` in previous steps of the CI)
Due to that, the E2E test for the ConfigMap will be added on a separate PR
=> Backport excludelist

cmd/resource-topology-exporter/main.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
In this PR we acknowledge the fact that giving access to the kubelet config file to the RTE is sometimes unwanted. Hence
1. we make the kubelet config file path optional and
2. we add an option to just tell the tool the policy, avoiding the need to read the kubelet config file.
=> make the discovery of the topology manager policy optional

.github/workflows/go.yml, cmd/resource-topology-exporter/main.go, config/examples/rte.yaml, manifests/resource-topology-exporter-config.yaml, manifests/resource-topology-exporter-ds.yaml, manifests/resource-topology-exporter.yaml, pkg/resourcemonitor/excludelist.go
We generalize the option to read the exclude list from a file
into reading a full configuration file which happens to
contain the exclude list definition.
This change will allow easy expansion of the configuration
at minimal cost.
=> config: generalize the excludelist configuration

cmd/resource-topology-exporter/main.go, go.mod, hack/get-manifests.sh, manifests/resource-topology-exporter-ds.yaml, manifests/resource-topology-exporter.yaml, pkg/nrtupdater/nrtupdater.go, pkg/prometheus/prometheus.go, pkg/resourcemonitor/noderesourcesaggregator.go, pkg/resourcemonitor/podresourcesscanner.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, test/e2e/e2e_test.go, test/e2e/metrics.go, test/e2e/utils/pod.go, vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go, vendor/modules.txt
This update implements a Prometheus endpoint for RTE.
It will expose two different types of metrics:
1. Number of API calls for PodresourceAPI that failed
2. A gauge that represents the latency that took every update of the NRT objects.
The server will listen on port 2112 by default
=> Prometheus endpoint for RTE

pkg/resourcemonitor/resourcemonitor_test.go
In some case like can be shown here: https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/23/checks?check_run_id=3393185481#step:5:23
the test might failed due to different order of objects between the slices.
=> Unittests: Sort []ContainerDevices before comparison

pkg/nrtupdater/nrtupdater.go, pkg/prometheus/prometheus.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, test/e2e/metrics.go
When reporting the operation delay metric, it's useful
to track which reason we had to trigger an operation.
For node resource objects, it's easy: it's always reactive, so we
hardcode the label; for podresources scan, it could be either
reactive (smart polling) or periodic (trigger update)
=> prometheus: add wakeup delay metrics

pkg/resourcemonitor/resourcemonitor_test.go
From time to time the resourcemonitor UT failed becasue the structs are equals but in different order.
Usually this is happening because the sorting of the structs isn't good enough.
In this update we added additional sort in which even if the ResourceName is identical we'll sort by DeviceIds, thus it increase the chances for both structs to look exactly the same.
If the error will still occur we'll add sort by third field and so on.
=> Improve sorting before comparing

cmd/resource-topology-exporter/main.go, go.mod, pkg/nrtupdater/nrtupdater.go, pkg/podrescli/client.go, pkg/prometheus/prometheus.go, pkg/resourcemonitor/resourcemonitor.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/modules.txt
We need a bit more powerful log package to be up to date with
best practices (most notably NFD) and to be able to toggle
messages depending on the verbosiness level.
klog is the default choice in the kube ecosystem, so we switch to it.
=> log: move to klog/v2

.github/workflows/e2e.yml, Makefile, pkg/version/version.go
Let's avoid defaults if we cannot safely detect the version
from the git tag: otherwise we can't distinguish a legit versioned
build from a build which used the fallback.
=> version: leave "undefined" if it cannot detect

pkg/resourcemonitor/resourcemonitor.go, pkg/resourcemonitor/resourcemonitor_test.go, pkg/version/version.go, test/e2e/topology_updater.go
Cleanup and further refinements following up https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/32. All the changes here are expected to preserve the behaviour introduced in the aforementioned PR, aiming to only simplifying the implementation, and expand the test coverage.
=> NFD resync cleanup

pkg/resourcemonitor/resourcemonitor.go, pkg/sysinfo/hugepages.go, pkg/sysinfo/hugepages_test.go, pkg/sysinfo/memory.go, pkg/sysinfo/memory_test.go, pkg/sysinfo/sysinfo.go
Extend the sysinfo package to extract per-NUMA memory information, and report it as per-NUMA capacity in resource monitor.
=> resmon: sysinfo: add and use per-NUMA memory info

test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodes/nodes.go, test/e2e/utils/pods/pods.go
During the e2e we deploy guaranteed pods that request some amount of resources and expecting to see the changes under the NRT object.
The problem is that on a cluster with multiple worker nodes, we don't know on which node the pod will land, and therefore we don't know which NRT object will change.
In order to solve the problem, we'll label an arbitrary worker node, with a unique label, at the beginning of the tests and use that label as a NodeSelector for all the pods.
=> Assign test pods using node selectors

pkg/sysinfo/hugepages_test.go, pkg/sysinfo/sysinfo.go
The pod resource API returns hugepages amount in bytes, so
we should calculate the total amount of hugepages also in bytes.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> sysinfo: fix hugepages information

test/e2e/rte/metrics.go
1. Get the correct Namespace for the test
2. Fix selector creation
With the previous implementation we ended up with the error shown here:
openshift-kni/resource-topology-exporter#28 (comment)
This patch fix that
=> Fix E2E test for metrics

test/e2e/rte/metrics.go, test/e2e/rte/rte.go
- Fix nil dereference pointer errors
- Do not check for a single RTE pod in the cluster
=> Fix additional E2E tests errors

.github/workflows/e2e.yml, test/e2e/rte/metrics.go
The e2e which runs under gh actions never tested the metrics tests.
This exposed us to a lot of errors and tests failures under the kni-org/RTE repo which consumes those tests and is based on the fact that they're reliable.
=> Add metrics test

pkg/resourcemonitor/resourcemonitor_test.go
#71 
TestNormalizeContainerDevices was  flaky due to a typo in the sort functions.
=> deflake resourcemonitor test

Makefile
Previously, the sorting was incorrectly always reporting
the first (oldest) tag to be set in the version.
=> Makefile: simplify and fix the detection of tag

test/e2e/rte/conditions.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go
We should wait relatively to the poll interval.
Removing hardcoded settings make the test more robust and
easier to adapt, and easier to consume for external projects.
=> e2e: remove hardcoded timeouts

test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/utils/pods/rtepod/rtepod.go
We use hardcoded value in the tests mostly (= 95% of the cases)
just because it's the simplest way. A more robust and flexible
way is to introspect the actual pod and extract the values
we care about. After all, there often is a set of correct values,
and we care more about state matching expectations (with again
a set of correct values, not a single one) rather than a exact check.
=> test: e2e: avoid hardcoded value, introspect pod

pkg/nrtupdater/nrtupdater.go
fix a typo (warningf vs warning - the former was correct) and streamline the logs
=> nrtupdater: fix logging

test/e2e/rte/conditions.go, test/e2e/topology_updater/topology_updater.go
- condition tests: do not run ginkgo.Expect under Eventually because it will result
in drop us out of Eventually.
- topology updater tests: check the generation instead of resource version, because generation updated
only when was change under the non status field.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> e2e: small fixes to tests

test/e2e/rte/conditions.go, test/e2e/rte/metrics.go
- the conditions test tries to remove (and later restore, but still)
the CRD, so it must be label Disruptive
- the metrics test is time-sensitive, so it must be labeled EventChain
=> e2e: add more test labels

test/e2e/utils/testenv/testenv.go
There are times when we are not fully aware of the ns where the tests are running, so if we want to look for a specific pod (by label) we can look in all namespaces instead.
=> e2e: change default ns to all ns

Makefile, go.mod, go.sum, tools/go-semver/go-semver.go, vendor/github.com/mdomke/git-semver/.gitignore, vendor/github.com/mdomke/git-semver/LICENSE, vendor/github.com/mdomke/git-semver/README.md, vendor/github.com/mdomke/git-semver/main.go, vendor/github.com/mdomke/git-semver/version/version.go, vendor/modules.txt
git-semver can create a proper semantic version,
while `git describe --tags` doesn't.
=> build: use git-semver to create the version

pkg/notification/notification.go, pkg/notification/notification_test.go, pkg/nrtupdater/nrtupdater.go, pkg/resourcetopologyexporter/resourceobserver.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
Make sure the goroutines are always handled on the calling sites; streamline all the relevant packages to expose the Run()/Stop() interface.
Resolves: #93
=> cleanup concurrency model

test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodetopology/nodetopology.go
When a guaranteed pod asks for nonintegral CPU request, we expect no changes under the amount of available resources in the NRT object.
This is not completely true and can make the test falky, because the pods gets its memory from the reserved pool (which in turn decreased from the available resources in the NRT object) and then the comparison failed, i.e. initial > final, when the test expect otherwise.
Let's change the test to compare only CPUs, which is eventually what we're mostly care about here.
=> e2e: deflake nonintegral cpu request test

.github/workflows/e2e.yml, .github/workflows/go.yml, hack/kind-config-e2e.yaml
Update kind, so we can use images based on kubernetes 1.23
Fixes: https://github.com/k8stopologyawareschedwg/resource-topology-exporter/issues/99
=> CI updates

.github/workflows/go.yml, .github/workflows/release.yml
In commit 79d078198d9189bf202c19071dfdf610a40649ff we partially updated to golang 1.17, but we left some gh actions lanes behind to 1.16 for no good reason. Let's fix that.
=> gh actions: finalize move to go 1.17

.github/workflows/release.yml
The release flow was mistakenly left behind
=> gh actions: upgrade kind to 1.23 fully

manifests/resource-topology-exporter-ds-kube-watch.yaml, manifests/resource-topology-exporter-ds-notif-file.yaml, manifests/resource-topology-exporter.yaml, test/e2e/rte/rte.go, test/e2e/utils/pods/rtepod/rtepod.go
RTE manifest layout has changed in latest deployer version, when underthe RTE container we splitted the command and arguments of RTE container into separte fileds.
This requires the FindNotificationFilePath to be looking for the --notify-file argument in the correct place.
Furthermore, we didn't check the returned error from the function, let's fix it as well.
=> e2e: fix FindNotificationFilePath function

cmd/resource-topology-exporter/main.go, pkg/nrtupdater/nrtupdater.go, pkg/podrescli/client.go, pkg/prometheus/prometheus.go
In few places we still use the old-way to construct errors.
Let's make another step towards go 1.13+ error handling.
See https://go.dev/blog/go1.13-errors
=> err: properly wrap errors

pkg/dump/dump.go, pkg/dump/dump_test.go, pkg/nrtupdater/nrtupdater.go
"utils" packages in golang are a antipattern:
https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
so let's repurpose our onw in something more meaningful.
`test/e2e/utils` will be addressed in a future PR.
=> pkg: repurpose `utils`

pkg/resourcetopologyexporter/resourceobserver.go
klog.Warningf does not support %w (overzealous replacement).
Use the good old %v instead to have the actual error logged.
=> pkg: resobv: fix formatting in Warningf

pkg/nrtupdater/nrtupdater.go, pkg/prometheus/prometheus.go, test/e2e/rte/metrics.go
Add metrics to report the traffic towards CRDs generated by the RTEs.
Even though issues like
https://github.com/kubernetes/kubernetes/issues/105932
https://github.com/kubernetes/kubernetes/issues/101755
should be solved, it's both cheap and useful to provide these metrics on RTE side, since we already have all the infrastructure
in place.
=> prometheus: add metrics about writes

Makefile, pkg/nrtupdater/fake/fake.go, tools/nrtstress/main.go
With small additions to our existing packages,
we can build a simple NRT load generator, useful to
test, troubleshoot and assess the scalability of RTE.
Note this tool is intentionally not shipped yet in releases:
still needs to mature a bit at least.
=> tools: add tool to generate fake load

.github/workflows/e2e.yml, cmd/resource-topology-exporter/main.go, cmd/resource-topology-exporter/main_test.go, hack/deploy-devices.sh, manifests/resource-topology-exporter-rbac.yaml, manifests/resource-topology-exporter.yaml, manifests/sample-devices/test-devicepluginA-config.yaml, manifests/sample-devices/test-devicepluginA-ds.yaml, pkg/resourcemonitor/resourcemonitor.go, pkg/resourcemonitor/resourcemonitor_test.go, test/e2e/rte/rte.go, test/e2e/utils/nodetopology/nodetopology.go, test/e2e/utils/pods/pods.go, test/e2e/utils/testenv/testenv.go
Creating new resources (usually devices) doesn't reflect under the NRT object.
The logic to support was already there, but the option to enable it was never exposed to the user. 
For the start, this option would be disabled by default until we'll be sure it's stable enough
=> Enable dynamic resource creation option

.github/workflows/release.yml, test/e2e/rte/conditions.go, test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/rte_local/rte_local.go, test/e2e/topology_updater/topology_updater.go
To make the releases more predictable, until we fix all the flakes,
run a selected subset of most critical e2e tests on the release
flow, and ONLY on the release flow.
On PRs, we will keep running the full suite.
=> e2e: ghactions: run only a subset of tests on release

.github/workflows/release.yml, test/e2e/rte/conditions.go, test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/rte_local/rte_local.go, test/e2e/topology_updater/topology_updater.go
To make the releases more predictable, until we fix all the flakes,
run a selected subset of most critical e2e tests on the release
flow, and ONLY on the release flow.
On PRs, we will keep running the full suite.
=> [release-0.7] e2e: ghactions: run only a subset of tests on release

pkg/nrtupdater/nrtupdater.go
nrtupdater is now stable since quite long time, and we have other means to troubleshoot it.
So bump up the logging level here.
=> logs: de-prioritize nrtupdater logs

.github/workflows/e2e.yml, .github/workflows/release.yml, test/e2e/rte/conditions.go, test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodetopology/nodetopology.go
use 1.24 images.
Switching to 1.24 -apparently just the client libs?- highlighted we need to do add podsecurity labeling.
Also noticed a source of flakiness and fixed it along the way.
=> gh actions: kind: bump to 1.24 with e2e fixes

.github/workflows/release.yml, test/e2e/utils/nodetopology/nodetopology.go
the release lane wants to run a well-defined subset of e2e tests, and in this flow we don't want to use devices with the sample-device-plugin.
So let's make sure we tolerate this flow without false negatives.
=> e2e: gh actions: handle missing devices

Makefile
Narrow down the build time by building only the minimal set of targets needed for container image.
Add or amend targets to make sure we can still build the full tool set, and we have no regressions.
=> Makefile: simplify targets

test/e2e/rte/conditions.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodes/nodes.go, test/e2e/utils/nodetopology/nodetopology.go, test/e2e/utils/pods/pods.go
rename k8s import for clarity, standardization and less ambiguity. No intended changes in behavior.
=> test: e2e: rename imports

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml, go.mod, pkg/ratelimiter/ratelimiter.go, pkg/ratelimiter/ratelimiter_test.go, pkg/resourcemonitor/resourcemonitor.go
1.19.3 is the most recent release at time of writing.
=> golang: update toolchain to 1.19.3

pkg/config/config.go, pkg/notification/notification.go, pkg/notification/notification_test.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
Up until now, it was not possible to disable the polling. The workaround was to set the polling interval to a insanely high value (like 1 day) but still, this is not a real fix.
The assumption was some form of polling was always useful, but over time this turns out to be not really true, and disabling polling is helpful at very least in testing.
Implying some form of polling was more than a historical combination of events than a conscious design decision, so let's fix it, better late than never.
=> notification: allow to disable the polling

test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/pods/pods.go
we have longstanding PFP flakes. The root cause is we asyncronously delete test pods, so the pod state leaks from a test to another.
This is because we delete test pod asynchronously in defer(), which leads to leak
A more robust approach is to synchronously delete pods inside ginkgo v2 `DeferCleanup`.
As extra bonus, we can now get rid of the `Cooldown` hack.
Found while testing/tuning #153
=> e2e: deflake e2e pfp tests

Makefile, images/Dockerfile
Add labels to the container image to hold the version and the git commit from which the binary was built.
Use opencontainer annotations defined
[here](https://github.com/opencontainers/image-spec/blob/main/annotations.md)
Issue: #150
=> Add labels to container image: version and commit

test/e2e/rte/rte.go
generic improvement: clarify timeout and polling values using `With{Timeout,Polling}` helpers.
Specific fix to the `StateDirectories` test: use the same (more correct) layout as per the `NotificationFile` test, reverting earlier "fix".
=> deflake event-based tests, another attempt

test/e2e/rte/rte.go, test/e2e/utils/pods/pods.go
we need to take a good look at our e2e suite and consider more heavy-handed approach because a lot of preconditions and assumptions are more and more be proven debatable or wrong.
For starters, however, address low-hanging fruits like panic on delete (which should never happen) and useless logs.
We will track overhaul of the suite separately.
=> e2e: fixes 20230207

pkg/config/config.go, pkg/notification/notification.go, test/e2e/rte/rte.go
The file-based notification is easier to secure and more reliable, because the state-dir approach handles deletion events with unavoidable delay - this is just how kubelet operates, we can't fix this.
=> notif: deprecate --kubelet-state-dir

pkg/config/config.go
It was just a copy/paste mistake when introduced.
About time to fix it for good.
=> config: fix option description

pkg/config/config.go, test/data/rteconfig/kubelet_tm_full.yaml, test/e2e/rte_local/rte_local.go, test/e2e/utils/runtime.go
Add support to read kubelet (topology manager) params from the config file, alongside the regular command line parameters.
For backward compatibility (and per unix traditions), the command line params still take precedence over the config file.
=> config: add support to get kubelet params

pkg/config/config.go
It was just a copy/paste mistake when introduced.
About time to fix it for good.
=> [release-0.10][manual] config: fix option description

go.mod, pkg/kubeconf/kubelet_config_file.go
Mixing yaml packages is a recipe for obscure bugs.
We prefer `sigs.k8s.io/yaml` already, so let's use it everywhere
=> [release-0.10][manual] kubeconf: yaml: always use sigs.k8s.io/yaml

pkg/config/config.go, test/data/rteconfig/kubelet_tm_full.yaml, test/e2e/rte_local/rte_local.go, test/e2e/utils/runtime.go
Add support to read kubelet (topology manager) params from the config file, alongside the regular command line parameters.
For backward compatibility (and per unix traditions), the command line params still take precedence over the config file.
=> [release-0.10][manual] config: add support to get kubelet params

go.mod, go.sum, pkg/resourcemonitor/resourcemonitor.go, test/e2e/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go, vendor/modules.txt
recently we gained a way to compute the PFP directly, considering all pods (standard behavior up until now) or only pods with exclusive resources allocated to them.
Expose the computation method as NRT attribute, to enable the consumers to know explicitely how the PFP was computed and react accordingly.
=> pfp: expose computation method

go.mod, go.sum, pkg/resourcemonitor/resourcemonitor.go, test/e2e/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go, vendor/modules.txt
recently we gained a way to compute the PFP directly, considering all pods (standard behavior up until now) or only pods with exclusive resources allocated to them.
Expose the computation method as NRT attribute, to enable the consumers to know explicitely how the PFP was computed and react accordingly.
Manual backport of #174
=> [release-0.11][manual] pfp: expose computation method

pkg/resourcemonitor/resourcemonitor.go
It's InfoS, so it uses a different format. Fix accordingly. Note the issue is only cosmetic, the code is NOT crashing.
backport of #182
=> [manual][release-0.11] resmon: fix the error message

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
time to update from the ancient 20.04.
Explicitely pin a version rather than follow the -latest floating tag.
=> ghactions: pin the runners to 22.04

test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodes/nodes.go
Improve the way we select and label the target node, adding a helper function to pick it and ensure that already labelled nodes are consistently picked up.
=> e2e: consistent target node pick

test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/namespace/namespace.go, test/e2e/utils/nodetopology/nodetopology.go
Create the test namespace explicitely, instead of
letting the framework do it. This is helpful to
enable namespace customization, like label injection.
=> e2e: explicit namespace creation

test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/namespace/namespace.go, test/e2e/utils/nodetopology/nodetopology.go
Create the test namespace explicitely, instead of letting the framework do it. This is helpful to
enable namespace customization, like label injection.
Additional improvements to logging to make troubleshooting easier
=> [release-0.12][manual] e2e: explicit namespace creation

images/Dockerfile
The centos 7 image is too old, let's bump to 8. We will probably update again soon, but one step at time.
Fixes: #175
=> images: bump to centos8

cmd/resource-topology-exporter/main.go, pkg/podreadiness/conditioninjector.go, pkg/resourcemonitor/resourcemonitor.go, pkg/resourcemonitor/resourcemonitor_test.go, pkg/resourcetopologyexporter/resourceobserver.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
Instead of creating a client in the relevant packages, accept a client from the caller and reuse the common client.
Fixes: #185
=> k8s: client: use common client

.github/workflows/e2e.yml, test/e2e/rte/metrics.go, test/e2e/utils/nodes/nodes.go
If memory serves, metrics just always take some time before to be populated (that's expected, documented and bening, but of course I don't have docs handy). If the metrics test executes too early, because ginkgo random ordering, that could explain the flakiness.
This PR won't fix the flakiness but will make it easier to understand if this is indeed the case.
=> e2e: utils: nodes: improve RTE metrics test troubleshooting

.github/workflows/e2e.yml, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/testenv/testenv.go
in order to make it easy to integrate the e2e test with other suites, let the nodeRef test to be conditionally skipped.
=> e2e: noderef: allow to skip test

.github/workflows/e2e.yml, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/testenv/testenv.go
in order to make it easy to integrate the e2e test with other suites, let the nodeRef test to be conditionally skipped.
=> [release-0.14][manual] e2e: noderef: allow to skip test

.golangci.yaml, Makefile, pkg/k8shelpers/k8shelpers.go, pkg/kubeconf/kubelet_config_file.go, pkg/notification/notification.go, pkg/nrtupdater/fake/fake.go, pkg/ratelimiter/ratelimiter.go, pkg/resourcemonitor/resourcemonitor.go, pkg/sysinfo/hugepages.go, pkg/sysinfo/memory.go, tools/nrtstress/main.go
Add new makefile target to run golangci-lint and to be used by developers.
Later (soonish) we will integrate golangci-lint in CI using the recommended GH action.
This PR also includes a batch of related fixes for the issues raised by the golangci-lint run.
=> golangci-lint add developer config and related fixes

.github/workflows/e2e.yml, .github/workflows/go.yml
we're promoting release-0.11 to LTS - because we want to support users stuck on 1.25. So enable CI on that branch.
=> gh actions: enable e2e on release-0.11

pkg/sysinfo/hugepages.go, pkg/sysinfo/hugepages_test.go, pkg/sysinfo/memory.go, pkg/sysinfo/memory_test.go
Add more validations when checking for hugepages, reducing the chance to read random junk in the system.
The layout of sysfs is stable and guaranteed; thus, should we encounter errors navigating it, we should
make sure to make noise and bubble them up, because it means something really weird happened.
=> sysinfo: hugepages: stricter checks, louder error handling

pkg/sysinfo/hugepages.go, pkg/sysinfo/hugepages_test.go, pkg/sysinfo/memory.go, pkg/sysinfo/memory_test.go
Add more validations when checking for hugepages, reducing the chance to read random junk in the system.
The layout of sysfs is stable and guaranteed; thus, should we encounter errors navigating it, we should
make sure to make noise and bubble them up, because it means something really weird happened.
=> [release-0.16][manual] sysinfo: hugepages: stricter checks, louder error handling 

pkg/sysinfo/hugepages.go, pkg/sysinfo/hugepages_test.go, pkg/sysinfo/memory.go, pkg/sysinfo/memory_test.go
Add more validations when checking for hugepages, reducing the chance to read random junk in the system.
The layout of sysfs is stable and guaranteed; thus, should we encounter errors navigating it, we should
make sure to make noise and bubble them up, because it means something really weird happened.
manual backport of #245
=> [release-0.15][manual] sysinfo: hugepages: stricter checks, louder error handling

.github/workflows/e2e.yml, images/Dockerfile, manifests/resource-topology-exporter-config.yaml, manifests/resource-topology-exporter-ds-notif-file.yaml, manifests/resource-topology-exporter.yaml, pkg/resourcemonitor/resourcemonitor.go, test/e2e/rte/rte.go
we want to setup TLS in CI, and doing it using config files is the preferred way. So let's start moving the existing config towards config files.
=> manifests: ci: switch to config files

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
This commit uplifts the github.com/jaypipes/ghw dependency to the v0.12.0 release (released July 2023). Included in the v0.11.0 release was a fix for detecting memory areas in hardware with NUMA architecture and Linux kernels > 5.19.0 as well as ARM platforms.
We are running resource-topology-exporter in our environments and ran into the aforementioned bug in ghw 0.9.0, thus this commit to uplift to a more modern ghw release.
Related https://github.com/jaypipes/ghw/issues/341
Signed-off-by: Jay Pipes <jaypipes@gmail.com>
=> uplift github.com/jaypipes/ghw to v0.12.0

.github/workflows/e2e.yml, test/e2e/rte/metrics.go
Since it is assumed that the RTE pod is created prior to execution of the e2e tests, we add additional CI lanes to tackle cases where Metric Address and port is explicitly specified. We add two cases, one where the metric mode is `http` and another one where `httptls`.
=> Add test cases for explicit Metric Address to be executed in CI

.github/workflows/e2e.yml, test/e2e/rte/metrics.go
Backport of https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/280 on release-0.18 branch.
Since it is assumed that the RTE pod is created prior to execution of the e2e tests, we add additional CI lanes to tackle cases where Metric Address and port is explicitly specified. We add two cases, one where the metric mode is http and another one where httptls.
=> [release-0.18][manual]Add test cases for explicit Metric Address to be executed in CI

.github/workflows/e2e.yml, test/e2e/rte/metrics.go
Backport of https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/280 on release-0.17 branch.
Since it is assumed that the RTE pod is created prior to execution of the e2e tests, we add additional CI lanes to tackle cases where Metric Address and port is explicitly specified. We add two cases, one where the metric mode is http and another one where httptls.
=> [release-0.17][manual]Add test cases for explicit Metric Address to be executed in CI

.github/workflows/e2e.yml, hack/get-manifests.sh, manifests/resource-topology-exporter-ds-notif-file.yaml, manifests/resource-topology-exporter.yaml, pkg/metrics/server/setup.go, test/e2e/rte/metrics.go, test/e2e/utils/pods/rtepod/rtepod.go
This is a reimplementation of https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/275 and https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/280 on 0.16 branch to achieve the same end to end behavior.
Currently we are serving insecure metrics on all IPv4 routable addresses on the local machine (0.0.0.0).
In this PR, we make the metric IP configurable in order to ensure that we listen for insecure metrics port only on one IP to reduce security vulnerability.
=> [release-0.16][manual] Limit serving of insecure metrics by allowing configurable IP

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
Bump ghw to v0.12.0 to consume the fix for detecting memory areas in hardware with NUMA architecture and Linux kernels > 5.19.0 as well as ARM platforms.
=> [release-0.17][manual] bump github.com/jaypipes/ghw to v0.12.0

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
Bump ghw to v0.12.0 to consume the fix for detecting memory areas in hardware with NUMA architecture and Linux kernels > 5.19.0 as well as ARM platforms.
=> [release-0.16][manual] bump github.com/jaypipes/ghw to v0.12.0

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
Bump ghw to v0.12.0 to consume the fix for detecting memory areas in hardware with NUMA architecture and Linux kernels > 5.19.0 as well as ARM platforms.
=> [release-0.15][manual] bump github.com/jaypipes/ghw to v0.12.0

.github/workflows/e2e.yml
turns out that if we target a specific pod we get the full available logs, vs a reduced log amount if we target by label
since in CI the RTE pod name is fairly predicatable and we have few pods, let's find (hackishly) the pod name and let's target it to get more context.
=> ghactions: more rte logs on error

.github/workflows/release.yml
Older versions will case the lane to auto-fail
=> ghactions: bump upload-artifact to v4

.github/workflows/release.yml
we missed to update one instance to v4
=> ghactions: fix missing upload-artifact reference

pkg/config/cfgfile.go, pkg/config/cfgfile_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/defaults_test.go, pkg/config/environ_test.go, pkg/config/flags.go, pkg/config/flags_test.go, pkg/config/validation.go, pkg/config/validation_test.go, test/e2e/rte_local/rte_local.go
add validation and restrictions about configuration paths,
to reduce the chance of path traversal vulnerabilities.
Most notably:
- config root path must be one of the allowed subpaths
- configlet are expected not to escape the configuration
directories
=> config: add path validation

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
Bump ghw to v0.12.0 to consume the fix for detecting memory areas in hardware with NUMA architecture and Linux kernels > 5.19.0 as well as ARM platforms.
=> [release-0.14][manual] bump github.com/jaypipes/ghw to v0.12.0

pkg/podres/filter/alwayspass.go, pkg/podres/filter/alwayspass_test.go, pkg/podres/filter/numalocality/numalocality.go, pkg/podres/filter/numalocality/numalocality_test.go, pkg/resourcemonitor/resourcemonitor.go
=> [release-0.20] resmon: podres: improve the debuggability of the PFP computation 

pkg/podres/filter/alwayspass.go, pkg/podres/filter/alwayspass_test.go, pkg/podres/filter/numalocality/numalocality.go, pkg/podres/filter/numalocality/numalocality_test.go, pkg/resourcemonitor/resourcemonitor.go
=> [release-0.18] resmon: podres: improve the debuggability of the PFP computation

pkg/podres/filter/alwayspass.go, pkg/podres/filter/alwayspass_test.go, pkg/podres/filter/numalocality/numalocality.go, pkg/podres/filter/numalocality/numalocality_test.go, pkg/resourcemonitor/resourcemonitor.go
=> [release-0.17] resmon: podres: improve the debuggability of the PFP computation

pkg/podres/filter/alwayspass.go, pkg/podres/filter/alwayspass_test.go, pkg/podres/filter/numalocality/numalocality.go, pkg/podres/filter/numalocality/numalocality_test.go, pkg/resourcemonitor/resourcemonitor.go
=> [release-0.16] resmon: podres: improve the debuggability of the PFP computation

pkg/podres/filter/alwayspass.go, pkg/podres/filter/alwayspass_test.go, pkg/podres/filter/numalocality/numalocality.go, pkg/podres/filter/numalocality/numalocality_test.go, pkg/resourcemonitor/resourcemonitor.go
=> [release-0.15] resmon: podres: improve the debuggability of the PFP computation

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
bump baseimages to ubuntu-latest (no real reason to get stuck in the past) and bump toolchain to 1.23, required by tests.
note module version is still 1.22.
=> [release-0.20] ci: ghactions bump baseimage and toolchain version

.github/workflows/e2e.yml, .github/workflows/go.yml
expand the list of branches on which we do want to run CI (stable branch).
We just don't enable CI on all the branches to save CI credits.
(cherry picked from commit 043f05f9224cf030a632e298d72954b29ef63f91)
=> [release-0.20] ghactions: ci: expand the stable branch list

.github/workflows/e2e.yml, .github/workflows/go.yml
expand the list of branches on which we do want to run CI (stable branch).
We just don't enable CI on all the branches to save CI credits.
(cherry picked from commit 043f05f9224cf030a632e298d72954b29ef63f91)
=> [release-0.21] ghactions: ci: expand the stable branch list

.github/workflows/e2e.yml, .github/workflows/go.yml
expand the list of branches on which we do want to run CI (stable branch).
We just don't enable CI on all the branches to save CI credits.
=> ghactions: ci: expand the stable branch list

images/Dockerfile
This is needed for e2e coverage testing network policies.
(cherry picked from commit 03cf14f352bbed67daecadc5036dc9943b0334a7)
=> [release-0.21] add ncat to the resource topology exporter image

images/Dockerfile
This is needed for e2e coverage testing network policies.
(cherry picked from commit 03cf14f352bbed67daecadc5036dc9943b0334a7)
=> [release-0.19] add ncat to the resource topology exporter image

.github/workflows/e2e.yml, .github/workflows/go.yml
unblock CI by updating to the latest CI images
and action versions.
=> [release-0.19] gh actions: bump CI config

cmd/resource-topology-exporter/main.go, go.mod, go.sum, pkg/pfpdump/pfpdump.go, pkg/pfpdump/pfpdump_test.go, pkg/resourcemonitor/resourcemonitor.go
the initial support for pfpstatus dump was rushed in and done synchronous in the scan loop. More than a potential performance issue, this is an issue of unnecessary coupling.
This PR repays this technical debt by uncoupling the pfpstatus dump part, using the existing, built-in pofingerprint package functionality.
=> resmon: decouple pfpstatus dump
