.github/workflows/e2e.yml, Makefile, hack/get-manifests.sh, manifests/resource-topology-exporter-ds.yaml, manifests/resource-topology-exporter-rbac.yaml, manifests/resource-topology-exporter.yaml, pkg/nrtupdater/nrtupdater.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go, test/e2e/rte.go, test/e2e/topology_updater.go, test/e2e/utils/pod.go
we increease the coverage of the topology updating tests, and we add the real rte-specific tests.
=> Add more e2e tests

.github/workflows/e2e.yml, Makefile, go.mod, hack/check-ds.sh, manifests/noderesourcetopologies_crd.yaml, vendor/modules.txt
The noderesourcetopology API is being updated, but this project is not ready to consume the new changes yet.
Let's make sure the state is consistent and the tests are reliable.
=> Improve the e2e tests reliability

cmd/resource-topology-exporter/main.go, pkg/podrescli/client.go, pkg/resourcetopologyexporter/resourcetopologyexporter.go
This change enables the client wrapping composition at minimal cost.
=> podrescli: add option to decorate a client

manifests/resource-topology-exporter-ds.yaml, pkg/resourcetopologyexporter/resourcetopologyexporter.go
cleanups of minor issues found during testing of https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/11
=> minor cleanups

test/e2e/topology_updater.go
a test started to fail lately; let's fix it.
=> ci: deflake

.github/workflows/release.yml
Add github action to release when a new tag is created.
=> gh actions: add release flow

Makefile, cmd/resource-topology-exporter/main.go
Looks like the reviewer left some minor things here and there; let's address them.
=> config: minor fixes after docopt removal

Makefile, cmd/resource-topology-exporter/main.go, go.mod, go.sum, pkg/version/version.go, test/e2e/rte.go, test/e2e/utils/runtime.go, vendor/github.com/hashicorp/go-version/CHANGELOG.md, vendor/github.com/hashicorp/go-version/LICENSE, vendor/github.com/hashicorp/go-version/README.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/github.com/hashicorp/go-version/go.mod, vendor/github.com/hashicorp/go-version/version.go, vendor/github.com/hashicorp/go-version/version_collection.go, vendor/modules.txt
1. The version will be defined in build time using ldflags
2. Added an e2e to make sure the version being injected properly
=> Add versioning mechanism

.github/workflows/go.yml, hack/check-format.sh
Add check to ensure the code is formatted according
to gofmt standards.
=> gh action: add gofmt check

.github/workflows/release.yml
Add code to push images to quay
=> gh actions: push to quay

.github/workflows/release.yml
=> gh actions: fix the release flow

.github/workflows/release.yml
=> gh actions: release flow fixes pt2

.github/workflows/release.yml
=> gh actions: fix the quay.io image push

.github/workflows/release.yml
=> gh action: fix the URL of the quay.io repo

.github/workflows/release.yml
=> gh actions: release: fix the release flow

test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodes/nodes.go, test/e2e/utils/pods/pods.go, test/e2e/utils/testconsts/testconsts.go
=> Move common constants into a separate package

pkg/utils/dump_test.go
=> tests: add basic test coverage for `dump`

test/e2e/rte/rte.go, test/e2e/utils/pods/pods.go
Similar to https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/58 but for the [RTE] tests
=> Deploy pods on specific node

pkg/resourcetopologyexporter/resourcetopologyexporter.go
The resourcetopologyexporter package has a utility object
confusingly called ResourceMonitor (compare with
resourcemonitor.ResourceMonitor).
Let's rename it ResourceObserver to improve the code clarity
(or at least reduce the code ambiguity) without any change
in behaviour
=> trivial rename: pkg: rte: rename internal helper

test/e2e/rte/rte.go, test/e2e/utils/pods/pods.go
Don't hardcoded data in the tests to make it easier
to consume them in other projects and to make them less fragile.
=> e2e: rte: avoid hardcoded data

pkg/resourcemonitor/resourcemonitor.go
When a device plugin doesn't report its NUMA affinity, we are very likely to get log spammed with
```
W0903 02:32:37.402438       1 resourcemonitor.go:198] zero capacity for resource "example.com/deviceA" on NUMA cell 0
W0903 02:32:37.402438       1 resourcemonitor.go:198] zero capacity for resource "example.com/deviceA" on NUMA cell 1
```
Log spamming is not just annoying: it causes log rotation and hides useful information.
Let's take steps to improve this state, trying to avoid to just remove a potentially useful log message.
=> resmon: reduce spam in the logs with NUMA affinity

pkg/resourcemonitor/resourcemonitor.go
When a device plugin doesn't report its NUMA affinity, we are very likely to get log spammed with
```
W0903 02:32:37.402438       1 resourcemonitor.go:198] zero capacity for resource "example.com/deviceA" on NUMA cell 0
W0903 02:32:37.402438       1 resourcemonitor.go:198] zero capacity for resource "example.com/deviceA" on NUMA cell 1
```
Log spamming is not just annoying: it causes log rotation and hides useful information.
Let's take steps to improve this state, trying to avoid to just remove a potentially useful log message.
=> [release-0.7] resmon: reduce spam in the logs with NUMA affinity

.github/workflows/e2e.yml, hack/get-manifests.sh, manifests/resource-topology-exporter.yaml, pkg/resourcemonitor/resourcemonitor.go
Add log to debug how PFP is computed; tune the default
verbosity settings too show the new logs.
=> manifests: resmon: debug pfp computation

pkg/resourcemonitor/resourcemonitor.go
log improvements, mostly focused on improving the PFP troubleshooting experience
=> Log cleanups 20220930

pkg/resourcemonitor/resourcemonitor.go
log improvements, mostly focused on improving the PFP troubleshooting experience
=> [release-0.7] Log cleanups 20220930 

.github/workflows/e2e.yml, .github/workflows/go.yml
based on
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
=> gh actions: update manifest

test/e2e/rte/rte.go
WIP: Add more logs to deflake the test.
Related-To: #117 
=> e2e: test: add logs to help deflake pfp test

test/e2e/rte/rte.go
Another attempt to simplify and at the same time deflake the longstanding unreliable smart poller test.
=> e2e: try again to simplify/deflake smart poller tests

pkg/resourcetopologyexporter/resourcetopologyexporter.go
In case the topology manager parameters where detected from the kubelet config, the attributes where incorrectly populated with the (empty) values from the command line, effectively discarded them.
The topologyPolicies field was however correctly populated.
=> rte: params: fix misdetection of the TM params

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
Move forward to fix deprecations
=> ghactions: update base actions

.github/workflows/e2e.yml, .github/workflows/release.yml
=> ghactions: kind: bump to 1.27.1

test/e2e/rte/conditions.go, test/e2e/rte/metrics.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go
General improvements and logger replacement for setting up the stage to get rid of k8s e2e framework
=> e2e: perquisites for untiying k8s e2e framework 

test/e2e/rte/conditions.go, test/e2e/rte/rte.go, test/e2e/topology_updater/topology_updater.go, test/e2e/utils/nodetopology/nodetopology.go
Use helper setters instead of positional arguments in `Eventually` to set polling interval and timeout. This is meant to make the code more readable, no
intended change in behavior.
=> e2e: use Eventually With{Polling,Timeout}

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml, go.mod
=> toolchain: update toolchain to 1.20

pkg/resourcemonitor/resourcemonitor.go
these are typpically logged once at startup, and they are controlled by high log verbosiness anyway
=> resmon: reintroduce debug logs

pkg/resourcemonitor/resourcemonitor.go
make sure we look in the env earlier
=> resmon: fix node logging

.github/workflows/e2e.yml, .github/workflows/release.yml
bump to the latest supported 1.27.z
=> ghactions: env: bump kind environment

.github/workflows/e2e.yml, .github/workflows/release.yml
bump to the latest supported 1.27.z
=> [release-0.15][manual] ghactions: env: bump kind environment

pkg/podres/client.go, pkg/podres/client_test.go, pkg/podres/fake.go
Add fake client, reading pre-rendered JSON responses from the given path.
This is meant to be used in test and development only
=> podres: client: add fake client

cmd/resource-topology-exporter/main.go, pkg/metrics/server/setup.go, pkg/podres/middleware/podexclude/podexclude.go
Fix wrong use of formats which somehow sneaked in up until now.
(cherry picked from commit 4c0954b7161fae5461cc198e9d18f28379b417d9)
=> [release-0.17][manual] klog: fix formatting

.github/workflows/e2e.yml, hack/get-manifests.sh, manifests/resource-topology-exporter.yaml, pkg/config/cfgdispatch.go, pkg/config/flags.go, pkg/metrics/server/setup.go
re-implement option to require client authentication on top of controller-runtime facilities.
Fixes: #267
=> metrics: restore client authentication option

.github/workflows/e2e.yml, go.mod, go.sum, hack/get-manifests.sh, manifests/resource-topology-exporter.yaml, pkg/config/cfgdispatch.go, pkg/config/flags.go, pkg/metrics/server/setup.go, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
backport fixes from main - cumulative cherry-picks PR
=> [release-0.18][manual] align with fixes from main

.github/workflows/e2e.yml, go.mod, go.sum, hack/get-manifests.sh, manifests/resource-topology-exporter.yaml, pkg/config/cfgdispatch.go, pkg/config/flags.go, pkg/metrics/server/setup.go, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
grab bag of misc fixes from the main branch
=> [release-0.18][manual] Backport fixes to branch 0.18

images/Dockerfile
centos 8 is long out of support. Let's move to stream9.
=> images: centos: 8->stream9

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
bump golang build toolchain to 1.23
=> Bump golang 1.23

.github/workflows/release.yml
we missed to update one instance to v4
=> [release-0.20][manual] ghactions: fix missing upload-artifact reference

pkg/config/cfgfile.go, pkg/config/flags.go, pkg/config/validation.go, pkg/notification/notification.go, pkg/resourcemonitor/resourcemonitor.go
sweeping scan of our public packages (`./pkg/...`) with gosec 2.21.4 and related fixes.
=> gosec analysis and fixes: 20241202

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
bump versions of the actions and of the base image
=> [release-0.14] ghactions: bump versions

.github/workflows/release.yml
escaped previous update by mistake
=> [release-0.14] ghactions: updated missing instance

.github/workflows/e2e.yml, .github/workflows/go.yml, .github/workflows/release.yml
resync with latest updates and fixes
=> ghactions: ci: bump versions of all actions

.github/workflows/e2e.yml, .github/workflows/release.yml, manifests/resource-topology-exporter-ds-notif-file.yaml, manifests/resource-topology-exporter.yaml
no reason to get stuck in the ancient 1.27.z
=> ghactions: bump to kind image v1.32.5
